# Generated by Django 3.1.5 on 2021-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(default='images/124180566_3771168516249284_3976912378791517206_o.jpg', upload_to='images'),
        ),
    ]
