# Generated by Django 3.1.5 on 2021-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_hotelreview_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='picture',
            field=models.ImageField(default='customer-icon.jpg', upload_to='images'),
        ),
    ]
