# Generated by Django 3.1.5 on 2021-03-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='gender',
            field=models.CharField(max_length=128),
        ),
    ]
