# Generated by Django 3.1.5 on 2021-03-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20210308_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('comment', models.TextField(max_length=1000)),
                ('rating_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=128)),
            ],
        ),
    ]
