# Generated by Django 3.1.5 on 2021-03-14 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_auto_20210310_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelreview',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='picture',
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='picture',
            field=models.ImageField(default='images/profile.png', null=True, upload_to='images'),
        ),
    ]
