# Generated by Django 3.1.5 on 2021-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_auto_20210314_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='picture',
            field=models.ImageField(default='images/saakadze.jpg', null=True, upload_to='images'),
        ),
    ]
