# Generated by Django 3.1.5 on 2021-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20210305_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_type2',
            field=models.CharField(choices=[('1', ''), ('2', 'No Parking')], default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(choices=[('1', 'Free WiFi'), ('2', 'No WiFi')], default='1', max_length=128),
        ),
    ]
