# Generated by Django 3.1.5 on 2021-03-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_hotelreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='customer_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
