# Generated by Django 3.1.5 on 2021-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20210308_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreview',
            name='review_type',
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='permission',
            field=models.BooleanField(default=True),
        ),
    ]
