# Generated by Django 3.1.5 on 2021-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_enter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enter',
        ),
        migrations.RemoveField(
            model_name='hotelreview',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='email',
            field=models.EmailField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='name',
            field=models.CharField(default=5, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='rating_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=128),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='picture',
            field=models.ImageField(default='bendu.jpg', upload_to='images'),
        ),
    ]
