# Generated by Django 3.1.5 on 2021-03-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_remove_hotelreview_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
