# Generated by Django 3.1.5 on 2021-03-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20210309_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
