# Generated by Django 3.1.5 on 2021-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210228_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
